name: jp_transliterate
description: "A Flutter plugin that converts Japanese Kanji into Furigana & Romaji, aiding language learners, reading assistance, and apps needing phonetic guides."
version: 1.0.2
homepage: https://github.com/thinhtrai1/JpTransliterate

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.thinhnd.jp_transliterate
        pluginClass: JpTransliteratePlugin
      ios:
        pluginClass: JpTransliteratePlugin
